-- MySQL Script generated by MySQL Workbench
-- Wed May  5 17:47:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oc_pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oc_pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oc_pizza` DEFAULT CHARACTER SET utf8mb4 ;
USE `oc_pizza` ;

-- -----------------------------------------------------
-- Table `oc_pizza`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`adresse` (
  `id_adresse` INT NOT NULL AUTO_INCREMENT,
  `numero_de_rue` INT NULL,
  `complement_de_rue` VARCHAR(45) NULL,
  `nom_de_rue` VARCHAR(50) NOT NULL,
  `immeuble` VARCHAR(25) NULL,
  `etage` VARCHAR(4) NULL,
  `escalier` VARCHAR(10) NULL,
  `appartement_numero` INT NULL,
  `code_postal` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `commentaire` VARCHAR(280) NULL,
  PRIMARY KEY (`id_adresse`),
  UNIQUE INDEX `id_adresse_UNIQUE` (`id_adresse` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `role` ENUM('client', 'pizzaiolo', 'livreur', 'hotesse', 'gerant', 'administrateur') NOT NULL DEFAULT 'client',
  `civilite` VARCHAR(10) NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `numero_telephone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `login` VARCHAR(254) NOT NULL,
  `mot_de_passe` VARCHAR(30) NOT NULL,
  `adresse_id_adresse` INT NOT NULL,
  `pizzeria_id_pizzeria` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`, `adresse_id_adresse`, `pizzeria_id_pizzeria`),
  UNIQUE INDEX `id_utilisateur_UNIQUE` (`id_utilisateur` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_utilisateur_adresse1_idx` (`adresse_id_adresse` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_utilisateur_pizzeria1_idx` (`pizzeria_id_pizzeria` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_adresse1`
    FOREIGN KEY (`adresse_id_adresse`)
    REFERENCES `oc_pizza`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_pizzeria1`
    FOREIGN KEY (`pizzeria_id_pizzeria`)
    REFERENCES `oc_pizza`.`pizzeria` (`id_pizzeria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`pizzeria` (
  `id_pizzeria` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `numero_telephone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `adresse_id_adresse` INT NOT NULL,
  PRIMARY KEY (`id_pizzeria`, `adresse_id_adresse`),
  UNIQUE INDEX `id_pizzeria_UNIQUE` (`id_pizzeria` ASC) VISIBLE,
  INDEX `fk_pizzeria_adresse1_idx` (`adresse_id_adresse` ASC) VISIBLE,
  CONSTRAINT `fk_pizzeria_adresse1`
    FOREIGN KEY (`adresse_id_adresse`)
    REFERENCES `oc_pizza`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`commande` (
  `id_commande` INT NOT NULL AUTO_INCREMENT,
  `pizzeria_id_pizzeria` INT NOT NULL,
  `utilisateur_id_utilisateur` INT NOT NULL,
  `statut_commande` ENUM('en attente', 'en préparation', 'prête', 'a retirer', 'en livraison', 'livrée', 'close', 'annulée') NOT NULL,
  `type_de_commande` ENUM('retrait', 'livraison') NOT NULL,
  `date` DATE NOT NULL,
  `heure` TIME NOT NULL,
  `heure_estimative` TIME NOT NULL,
  `montant_ttc` DECIMAL(6,2) NOT NULL,
  `methode_de_paiement` ENUM('espèce', 'carte bancaire', 'titre restaurant', 'paypal') NULL,
  `paiement_ok` BOOLEAN NOT NULL,
  PRIMARY KEY (`id_commande`, `pizzeria_id_pizzeria`, `utilisateur_id_utilisateur`),
  INDEX `fk_commande_utilisateur_idx` (`utilisateur_id_utilisateur` ASC) VISIBLE,
  INDEX `fk_commande_pizzeria_idx` (`pizzeria_id_pizzeria` ASC) VISIBLE,
  UNIQUE INDEX `id_commande_UNIQUE` (`id_commande` ASC) VISIBLE,
  CONSTRAINT `fk_commande_utilisateur`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `oc_pizza`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_pizzeria`
    FOREIGN KEY (`pizzeria_id_pizzeria`)
    REFERENCES `oc_pizza`.`pizzeria` (`id_pizzeria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`categorie` (
  `id_categorie` INT NOT NULL,
  `categorie` ENUM('entrée', 'pizza', 'salade', 'bruschetta', 'dessert', 'boisson', 'sauce') NOT NULL,
  `sous_categorie` ENUM('base crème', 'base tomate', 'vegan', 'spéciale', 'sucrée', 'glacé', 'patisserie', 'gazeuse', 'plate') NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`produit` (
  `id_produit` INT NOT NULL AUTO_INCREMENT,
  `categorie_id_categorie` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `composition` VARCHAR(1000) NULL,
  `prix_vente_ht` DECIMAL(6,2) NULL,
  `prix_vente_ttc` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id_produit`, `categorie_id_categorie`),
  UNIQUE INDEX `id_produit_UNIQUE` (`id_produit` ASC) VISIBLE,
  INDEX `fk_produit_categorie1_idx` (`categorie_id_categorie` ASC) VISIBLE,
  CONSTRAINT `fk_produit_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `oc_pizza`.`categorie` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`ligne_de_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`ligne_de_commande` (
  `commande_id_commande` INT NOT NULL,
  `id_ligne_de_commande` INT NOT NULL,
  `produit_id_produit` INT NOT NULL,
  `quantite` INT NOT NULL,
  `prix_ligne_ttc` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`commande_id_commande`, `id_ligne_de_commande`, `produit_id_produit`),
  INDEX `fk_ligne_de_commande_produit_idx` (`produit_id_produit` ASC) VISIBLE,
  INDEX `fk_ligne_de_commande_commande_idx` (`commande_id_commande` ASC) VISIBLE,
  CONSTRAINT `fk_ligne_de_commande_produit`
    FOREIGN KEY (`produit_id_produit`)
    REFERENCES `oc_pizza`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne_de_commande_commande`
    FOREIGN KEY (`commande_id_commande`)
    REFERENCES `oc_pizza`.`commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`composant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`composant` (
  `id_composant` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `volumetrie` DECIMAL(7,2) NULL,
  `unite_mesure` ENUM('gramme(s)', 'mililitre(s)', 'centilitre(s)', 'pièce(s)', 'tranche(s)') NULL,
  PRIMARY KEY (`id_composant`),
  UNIQUE INDEX `id_ingredient_UNIQUE` (`id_composant` ASC) VISIBLE,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `composant_id_composant` INT NULL,
  `produit_id_produit` INT NULL,
  `quantite` DECIMAL(7,2) NOT NULL,
  `conditionnement` ENUM('boite(s)', 'bouteille(s)', 'pot(s)', 'sachet(s)', 'canette(s)', 'pièce(s)') NOT NULL,
  `pizzeria_id_pizzeria` INT NOT NULL,
  PRIMARY KEY (`id_stock`, `pizzeria_id_pizzeria`),
  INDEX `fk_stock_pizzeria_idx` (`pizzeria_id_pizzeria` ASC) VISIBLE,
  INDEX `fk_stock_composant1_idx` (`composant_id_composant` ASC) VISIBLE,
  INDEX `fk_stock_produit1_idx` (`produit_id_produit` ASC) VISIBLE,
  CONSTRAINT `fk_stock_pizzeria`
    FOREIGN KEY (`pizzeria_id_pizzeria`)
    REFERENCES `oc_pizza`.`pizzeria` (`id_pizzeria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_composant1`
    FOREIGN KEY (`composant_id_composant`)
    REFERENCES `oc_pizza`.`composant` (`id_composant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_produit1`
    FOREIGN KEY (`produit_id_produit`)
    REFERENCES `oc_pizza`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`recette` (
  `produit_id_produit` INT NOT NULL,
  `recette` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`produit_id_produit`),
  CONSTRAINT `fk_recette_produit1`
    FOREIGN KEY (`produit_id_produit`)
    REFERENCES `oc_pizza`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc_pizza`.`utilisation_composant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`utilisation_composant` (
  `recette_produit_id_recette_produit` INT NOT NULL,
  `composant_id_composant` INT NOT NULL,
  `quantite_preparation` DECIMAL(6,2) NOT NULL,
  `unite_mesure` ENUM('gramme(s)', 'mililitre(s)', 'centilitre(s)', 'pièce(s)', 'tranche(s)') NOT NULL,
  PRIMARY KEY (`recette_produit_id_recette_produit`, `composant_id_composant`),
  INDEX `fk_detail_ingredient_recette_idx` (`recette_produit_id_recette_produit` ASC) VISIBLE,
  INDEX `fk_utilisation_composant_composant1_idx` (`composant_id_composant` ASC) VISIBLE,
  CONSTRAINT `fk_detail_ingredient_recette1`
    FOREIGN KEY (`recette_produit_id_recette_produit`)
    REFERENCES `oc_pizza`.`recette` (`produit_id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisation_composant_composant1`
    FOREIGN KEY (`composant_id_composant`)
    REFERENCES `oc_pizza`.`composant` (`id_composant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
